const transitions=Object.freeze({received:['validated'],validated:['recommendation_ready','manual_only'],recommendation_ready:['dispatcher_review'],dispatcher_review:['dispatched','cancelled'],manual_only:['dispatcher_review'],dispatched:[],cancelled:[]});
const ageMinutes=(value,now)=>(now-Date.parse(value))/60000;
const hasCapabilities=(unit,needed)=>needed.every(x=>(unit.capabilities||[]).includes(x));
function distanceKm(a,b){const rad=x=>x*Math.PI/180,R=6371,dLat=rad(b.lat-a.lat),dLon=rad(b.lng-a.lng),v=Math.sin(dLat/2)**2+Math.cos(rad(a.lat))*Math.cos(rad(b.lat))*Math.sin(dLon/2)**2;return 2*R*Math.atan2(Math.sqrt(v),Math.sqrt(1-v));}
export function validateIncident(input){const errors=[];if(!input.incident?.externalId)errors.push('incident.externalId is required');if(![1,2,3,4,5].includes(input.incident?.priority))errors.push('incident.priority must be 1-5');if(!Number.isFinite(input.incident?.location?.lat)||!Number.isFinite(input.incident?.location?.lng))errors.push('incident.location coordinates are required');if(!input.source?.system||!input.source?.eventId||!input.source?.version||Number.isNaN(Date.parse(input.source?.receivedAt||'')))errors.push('versioned incident source provenance is required');if(!Array.isArray(input.units)||input.units.length===0)errors.push('unit status is required');if(!Array.isArray(input.hospitals)||input.hospitals.length===0)errors.push('hospital capacity is required');if(!input.traffic?.version||Number.isNaN(Date.parse(input.traffic?.observedAt||'')))errors.push('traffic snapshot is required');if(!input.failSafe?.fallbackChannel||!input.failSafe?.staleAfterMinutes)errors.push('failSafe fallbackChannel and staleAfterMinutes are required');return{valid:errors.length===0,errors};}
export function evaluateDispatch(input,now=Date.now()){const staleAfter=Number(input.failSafe.staleAfterMinutes),needed=input.incident.requiredCapabilities||[];const staleTraffic=ageMinutes(input.traffic.observedAt,now)>staleAfter;const eligibleUnits=input.units.filter(u=>u.status==='available'&&hasCapabilities(u,needed)&&ageMinutes(u.observedAt,now)<=staleAfter).map(u=>({...u,distanceKm:Number(distanceKm(input.incident.location,u.location).toFixed(3))})).sort((a,b)=>a.distanceKm-b.distanceKm||String(a.id).localeCompare(String(b.id)));const eligibleHospitals=input.hospitals.filter(h=>Number(h.availableBeds)>0&&ageMinutes(h.observedAt,now)<=staleAfter).sort((a,b)=>Number(b.availableBeds)-Number(a.availableBeds)||String(a.id).localeCompare(String(b.id)));const manualOnly=staleTraffic||eligibleUnits.length===0||eligibleHospitals.length===0;return{manualOnly,reasons:[staleTraffic?'stale_traffic':null,eligibleUnits.length===0?'no_eligible_unit':null,eligibleHospitals.length===0?'no_current_capacity':null].filter(Boolean),recommendedUnitId:manualOnly?null:eligibleUnits[0].id,recommendedHospitalId:manualOnly?null:eligibleHospitals[0].id,eligibleUnitCount:eligibleUnits.length,professionalDispatcherReviewRequired:true,automatedDispatchAllowed:false};}
export function assertTransition(from,to,actor,record,command){if(!(transitions[from]||[]).includes(to))throw new Error(`transition ${from} -> ${to} is not allowed`);if(to==='dispatched'){if(!['dispatcher','dispatch_supervisor','admin'].includes(actor.role))throw new Error('dispatcher authority required');if(String(actor.id)===String(record.created_by))throw new Error('recommendation author cannot issue the dispatch command');if(record.priority===1&&!['dispatch_supervisor','admin'].includes(actor.role))throw new Error('priority 1 dispatch requires supervisor authority');if(!command?.cadCommandId||!command?.radioAcknowledged)throw new Error('CAD command id and radio acknowledgement are required');}}
export{transitions};

